name: "WireGuard Client"
version: "1.1.0"
slug: "wireguard-client"
description: "Connect Home Assistant as WireGuard VPN client to external server"
url: "https://github.com/DEIN-USERNAME/ha-wireguard-client"
startup: "services"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
privileged:
  - NET_ADMIN
  - SYS_MODULE
host_network: true
hassio_api: true
options:
  interface:
    address: "10.0.0.2/24"
    private_key: ""
    dns: ""
  peer:
    public_key: ""
    endpoint: "vpn.example.com:51820"
    allowed_ips: "10.0.0.0/24"
    persistent_keepalive: 25
    preshared_key: ""
schema:
  interface:
    address: str
    private_key: password
    dns: "str?"
  peer:
    public_key: password
    endpoint: str
    allowed_ips: str
    persistent_keepalive: "int(0,65535)"
    preshared_key: "password?"
