name: "WireGuard Client"
version: "1.6.0"
slug: "wireguard-client"
description: "Connect Home Assistant as WireGuard VPN client to external server"
url: "https://github.com/JSchmid6/ha-wireguard-client-addon"
startup: "services"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
privileged:
  - NET_ADMIN
  - SYS_MODULE
host_network: true
options:
  interface:
    address: "10.0.0.2/24"
    private_key: ""
  peer:
    public_key: ""
    endpoint: "vpn.example.com:51820"
    allowed_ips: "10.0.0.0/24"
    persistent_keepalive: 25
  nat:
    enabled: false
    allowed_targets: []
    port_forwards: []
schema:
  interface:
    address: str
    private_key: password
    dns: "str?"
    mtu: "int(1280,1500)?"
  peer:
    public_key: password
    endpoint: str
    allowed_ips: str
    server_allowed_ips: "str?"
    persistent_keepalive: "int(0,65535)"
    preshared_key: "password?"
  nat:
    enabled: bool
    interface: "str?"
    allowed_targets:
      - "str?"
    port_forwards:
      - "str?"
